import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Header from "@/components/navigation2";
import Providers from "./provider";
import Navigation from "@/components/header"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>


        <Providers>
          <Navigation/>
        {/* <Header/> */}

        <main className="relative overflow-hidden">

        {children}
        </main>
        
        </Providers>
        </body>
    </html>
  );
}
